### ISSUE TITLE
wsdd showing error and hangs in the terminal

### ISSUE THREAD

**Issue by miteshparmar1** [christgau/wsdd#119]
I upgraded to the latest version of Python on the Raspberry Pi; 3.7.3

I followed your installation instructions for wsdd:
**Generic Installation Instructions**
_No installation steps are required. Just place the wsdd.py file anywhere you want to, rename it to wsdd, and run it from there. The init scripts/unit files assume that wsdd is installed under /usr/bin/wsdd or /usr/local/bin/wsdd in case of FreeBSD. There are no configuration files. No special privileges are required to run wsdd, so it is advisable to run the service as an unprivileged user such as nobody.

The etc directory of the repo contains sample configuration files for different init(1) systems, namely FreeBSD's rc.d, Gentoo's openrc, and systemd which is used in most contemporary Linux distros. Those files may be used as templates for their actual usage. They are likely to require adjustments to the actual distribution/installation where they are to be used._

When I run the script using ./wsdd I receive the following error and the program hangs in the Terminal:
```
2021-09-18 17:53:02,624:wsdd WARNING(pid 3399): no interface given, using all interfaces
2021-09-18 17:53:02,978:wsdd ERROR(pid 3399): error while sending packet on wg0: [Errno 126] Required key not available
2021-09-18 17:53:03,214:wsdd ERROR(pid 3399): error while sending packet on wg0: [Errno 126] Required key not available
2021-09-18 17:53:03,687:wsdd ERROR(pid 3399): error while sending packet on wg0: [Errno 126] Required key not available
2021-09-18 17:53:04,189:wsdd ERROR(pid 3399): error while sending packet on wg0: [Errno 126] Required key not available
![Screenshot 2021-09-18 at 18 13 45](https://user-images.githubusercontent.com/40478322/133896950-662bc0b9-b086-429b-b0ff-d15362b701c2.png)
```

**Comment by christgau** [comment]
The error messages are not fatal. In addition, they appear to be related to a WireGuard VPN interface which is not configured correctly. There nothing, wsdd can to about this. Despite that, you should consider the warning and start wsdd only on specific interfaces.

It is very unlikely that wsdd really hangs here, but it just don't print anything besides warnings and errors. If you want to see some more output, make it verbose. You may also think about the usage and run wsdd as a daemon. 

Closing the issue because it appears there are no actual errors or misbehavior.
