### ISSUE TITLE
Invalid syntax 

### ISSUE THREAD

**Issue by kmsmith222** [christgau/wsdd#120]
OS : Ubuntu 20.04 
I did change the interfaces names to ethX, not sure if that has anything to do with it. 

When i restart WSDD this shows up in the log: 
-- 
wsdd[18338]:   File "/usr/bin/wsdd", line 47
 wsdd[18338]:     class MulticastHandler:
 wsdd[18338]:         ^
wsdd[18338]: SyntaxError: invalid syntax
--
And it fails to start..Tisis new since I havent had a reason to mess with it for a few months.

**Comment by christgau** [comment]
This really does not appear to be an issue on the wsdd side. There is also an action since a few commits that checks for syntax errors: 
https://github.com/christgau/wsdd/blob/b86c24190d8ea169db68eb0658f23ca44dadb095/.github/workflows/static-analyses.yml#L23-L24

and it did not reveal any. Therefore I am closing this issue.
