### ISSUE TITLE
wsdd.xml generates parse error when running firewall-cmd --check-config

### ISSUE THREAD

**Issue by ronchristie** [christgau/wsdd#128]
Hi Steffan,
When I run firewall-cmd --check-config I get the following:
Error: PARSE_ERROR: 'wsdd.xml': Unexpected element include

My wsdd.xml is as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Web Services Dynamic Discovery host daemon</short>
  <description>wsdd implements a Web Service Discovery host daemon. This enables (Samba) hosts, like your local NAS device, to be found by Web Service Discovery Clients like Windows.</description>
  <port port="3702" protocol="udp"/>
  <destination ipv4="239.255.255.250" ipv6="FF02::C"/>
  <include service="wsdd-http"/>
</service>
```
I believe this is the unmodified version of the file that installs with the CentOS 7 package.
Is this anything I should be concerned about?

**Comment by christgau** [comment]
Hi Ron,

thanks for opening that issue, but this is nothing I can help with. The firewall config file is provided by your distro's package maintainers. The wsdd sources do not provide that config file. You may contact downstream (https://packages.fedoraproject.org/pkgs/wsdd/wsdd/ looks promising) to ask for that issue, but the error message sounds like something fundamentally is flawed here. I would assume that other packages with similar configs would be affected as well. Thus, you could check your environment with other configs first. That said, I'm closing that issue here.
