### ISSUE TITLE
Does WSDD make a host appear in Network > Shared Folder (SMB) of Manjaro?

### ISSUE THREAD

**Issue by FlexMcMurphy** [christgau/wsdd#136]
Hello,

I am a bit confused about WSDD, can someone help please?

In one house I have OpenWrt as my router. I have a few Raspberry Pis on that LAN, each have Samba server and Samba shares and they also each have WSDD installed on them. With this set up when I start up Manjaro on my laptop I can go to the Dolphin File Explorer > Network > Shared Folder (SMB) and then all the Pis on that LAN auto-populate into that file explorer window so from there I can click in to them and browse their Samba shares.

However I made another installation in a different house. This time there is an ISP modem/router set up (no OpenWrt) so all I have is a Raspberry Pi attached to that router and the Pi is running Ubuntu server with Samba server, a few Samba shares and no WSDD. On this setup when I go to my Manjaro Laptop and click on Dolphin File Explorer > Network > Shared Folder (SMB) now that Pi running Ubuntu server does NOT auto-populate into that file explorer window. Instead I have to type `smb://[ip address]` into the address bar and then I can see the Samba shares on that Pi.

**My Question:**
Instructions on this GitHub appear to focus on how WSDD facilitates network browsing of LAN hosts in the **Windows OS Network Neighborhood** which is now lost since the demise of NETBIOS. But does WSDD also enable the same functionality in a network browsing Linux OS client? Otherwise I don't understand why my Raspberry Pis in one house (each with WSDD installed) auto-populate in the Dolphin File Explorer of Manjaro but this does not happen on the same laptop when I am in the other house?

Cheers,

Flex

**Comment by christgau** [comment]
> Instructions on this GitHub appear to focus on how WSDD facilitates network browsing of LAN hosts in the Windows OS Network Neighborhood 

That's exactly the purpose of wsdd.

> But does WSDD also enable the same functionality in a network browsing Linux OS client?

Not intentionally. 

I don't know what all the different file managers (consider Thunar, Dolphin, Nautilus/Gnome File Manager) use under the hood to detect network hosts. I presume, they use zeroconf/avahi. So you may check if you see an according daemon on the Samba hosts in the OpenWRT environment which announces the file server. Take a look at `/etc/avahi/services` to see if you can find a service definition for Samba. Then check if you see similar things on the other setup. Also check the firewall.

Since this is actually out of wsdd's scope, I'm closing the issue.

**Comment by FlexMcMurphy** [comment]
Just confirming that I simply had to [install Avahi](https://www.poftut.com/linux-avahi-daemon-tutorial-examples/) on my Ubuntu server for that host to auto-appear in the Dolphin File Manager in Manjaro:
```
sudo apt install avahi-daemon
sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon
```

Cheers,

Flex
