### ISSUE TITLE
Ubuntu 22.04 dist missing (jammy main)

### ISSUE THREAD

**Issue by lucasfcnunes** [christgau/wsdd#147]
```
# wsdd.list
deb https://pkg.ltec.ch/public/ jammy main
```

![image](https://user-images.githubusercontent.com/29926675/183316619-bcb37111-af10-423d-8e37-cb1e67b36d5e.png)

**Comment by fxrb** [comment]
Once Ubuntu 22.04 is released I will add wsdd to the repository. The release is delayed for the time being, please also read the [Release Notes for Ubuntu 22.04](https://wiki.ubuntu.com/JammyJellyfish/ReleaseNotes/Kubuntul), especially:

> Upgrades to 22.04 LTS are currently not enabled (due a bug with snapd and update-notifier) but will be in the next couple of days.

**Comment by christgau** [comment]
Just for clarification: Wasn't the [idea to kind of phase out the repository](https://github.com/christgau/wsdd/issues/19#issuecomment-1044357413) (see #19), since wsdd has landed (at least) [in Ubuntu 22.04 LTS ](https://packages.ubuntu.com/jammy/wsdd)? Ok, fair enough, the Readme must be updated anyways (see #146, #130) 😉

**Comment by fxrb** [comment]
> Just for clarification: Wasn't the [idea to kind of phase out the repository](https://github.com/christgau/wsdd/issues/19#issuecomment-1044357413) (see #19), since wsdd has landed (at least) [in Ubuntu 22.04 LTS ](https://packages.ubuntu.com/jammy/wsdd)?

Agreed when talking about Ubuntu/Kubuntu, but not Debian (for now it is in testing). Frankly I don't know if I will find the time to  monitor all distributions to provide some sort of _distribution specific fade out_ of the repository. If I do, I will intentionally **not** provide wsdd for new releases for which an official repository exists, hence forcing user to switch.
In accordance to that I revoke what I said in my post https://github.com/christgau/wsdd/issues/147#issuecomment-1207801407:  wsdd will **not** make it into the repository at https://pkg.ltec.ch/public/ for **Ubuntu 22.04** since there is an official repository. If you would like to install wsdd on Ubuntu 22.04 please install it from the official repository like any other package.

> Ok, fair enough, the Readme must be updated anyways (see #146, #130) wink

Yes, this should be done ASAP. Probably it is best to provide a list of distributions/releases which still require my repository due to the lack of an official repository. This list should then get shorter and shorter over time until my repository would remain useful only for legacy releases.

**Comment by christgau** [comment]
> Agreed when talking about Ubuntu/Kubuntu, but not Debian (for now it is in testing).

Right.

> wsdd will not make it into the repository at https://pkg.ltec.ch/public/ for Ubuntu 22.04 since there is an official repository

Understood. Consequently, I close this issue. 

> > Ok, fair enough, the Readme must be updated anyways (see https://github.com/christgau/wsdd/pull/146, https://github.com/christgau/wsdd/pull/130) wink
>
> Yes, this should be done ASAP.

As soon as time allows, I'll update the README (and other stuff)

> Probably it is best to provide a list of distributions/releases which still require my repository due to the lack of an official repository. 

Good idea. Will take that into account.
