### ISSUE TITLE
Feature request: include upstream with Samba instead of distros?

### ISSUE THREAD

**Issue by frankk74** [christgau/wsdd#172]
Steffen, thank you (danke) for your cool work, I have been using it for a couple of years!

I’m crossing referencing this issue over to upstream samba hoping they will include your work somehow? I hope this is okay with you?

There is a minimal distro called Dietpi which is a mini Debian for SBC’s and over there someone requested that they add wssd to that distro: 

https://github.com/MichaIng/DietPi/discussions/5244

And it has been hanging around in sambaland as well (since 2007!):

Feature request: Samba 4 should support LLMNR
https://bugzilla.samba.org/show_bug.cgi?id=4545

**Comment by frankk74** [comment]
Seems they aren’t interested at all. There is one other request for the functionality. I’m closing this issue. Seems the same person who shutdown my request also shutdown the other one:  https://bugzilla.samba.org/show_bug.cgi?id=11473

**Comment by christgau** [comment]
Frank, thanks you (danke) for your efforts and your interest in pushing wsdd into Samba. 

I honestly have mixed feelings on this. I would very much appreciate if wsdd becomes a part of Samba because the usage of wsdd along with Samba is a natural thing. Being part of Samba may also enable for better integration, like starting and stopping when Samba daemon comes up/shuts down. But such things can also be done by other means. Contrary, wsdd is an implementation of the WSD protocol that is tightly bound to Samba. The protocol itself is more generic and allows for more than just showing the little computer icon in explorer (tbh, the only other practical use case I know of is showing a printer/scanner icon there). In that sense, wsdd is actually limited compared to wsdd2, e.g. Thus, one may choose a more generic implementation to be part of the Samba suite, since one could also announce printing services - I think. 

Transferring the Unix philosophy of having programs do one thing and do it well to software packages, I'm absolutely fine to let wsdd live outside the Samba ecosystem. In addition, one now has the choice of what to install as an WSD implementation. If you don't like Python for whatever reason, go for wsdd2, otherwise choose wsdd 😉 

Even if an integration of wsdd would be considered I would be happy if someone does a code review or even an security audit (see #17) if that is possible. 

Putting all that aside. The Samba bugs seem to miss the point or appear to be unrelated.

Bug [4545](https://bugzilla.samba.org/show_bug.cgi?id=4545) is about LLMNR to be integrated in Samba. LLMNR is something that wsdd2 can handle, but not wsdd. I once considered to support LLMNR but noticed that a) wsdd2 had this already and b) systemd as well as other implementations support it as well, so i dropped that idea since I did not wanted wsdd to be a Python copy of wsdd2 (note that wsdd appeared on Github before wsdd2). I also recalled the UNIX philosophy (see above) and thought that LLMNR should be done by another tool.

Bug [11473](https://bugzilla.samba.org/show_bug.cgi?id=11473) is identical to the above by about 50% 😉In the end the discussion appears to be centered on LLMNR again. 

So in case you want to raise the question again, open up a new ticket on WSD support alone. However, I also can understand the point that Björn Jacke is making in [his comment](https://bugzilla.samba.org/show_bug.cgi?id=11473#c15): 

> What are the benefits having this inside of Samba?

If there no actual strong benefits (see above), I don't see a reason for being port of Samba as well. I can live very well with the current situation but wouldn't oppose if the Samba folks change their mind...
