### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by jwaltrip4** [christgau/wsdd#175]
Trying to install and getting:

curl –o /etc/systemd/system/wsdd.service https://raw.githubusercontent.com/christgau/wsdd/master/src/wsdd.py

returns:  curl: (3) URL using bad/illegal format or missing URL  --> folowed by writing python script to screen

THEN:

sudo echo "deb [signed-by=/usr/share/keyrings/wsdd.gpg] https://pkg.ltec.ch/public/ ${UBUNTU_CODENAME:-${VERSION_CODENAME:-UNKNOWN}} main" > /etc/apt/sources.list.d/wsdd.list

the sudo apt install wsdd and I get:

Unable to locate package wsdd

**Comment by christgau** [comment]
> curl –o /etc/systemd/system/wsdd.service https://raw.githubusercontent.com/christgau/wsdd/master/src/wsdd.py
> 
> returns: curl: (3) URL using bad/illegal format or missing URL --> folowed by writing python script to screen

That's not an wsdd issue and - frankly speaking - I don't understand why one would open an issue at the project site for such a thing. 

However: Please make sure you read the whole curl error message and do not only post the last one you see. Here's what I see, when I copy and past the command as you mentioned above (not sure if it is really what you typed into the terminal):

```
curl: (3) Failed to convert –o to ACE; string contains a disallowed character

curl: (3) URL using bad/illegal format or missing URL
```

> sudo echo "deb [signed-by=/usr/share/keyrings/wsdd.gpg] https://pkg.ltec.ch/public/ ${UBUNTU_CODENAME:-${VERSION_CODENAME:-UNKNOWN}} main" > /etc/apt/sources.list.d/wsdd.list

I'm pretty confident, that the destination (/etc/apt/sources.list.d/wsdd.list) file was not written . 

> the sudo apt install wsdd and I get:
> Unable to locate package wsdd

Sure, probably due to the former issue with the list file, but also because you missed to update/fetch package list of from the configured sources. Please refer carefully to the readme on how to install wsdd on Debian-based distros.

Closing this issue, because it is none.
