### ISSUE TITLE
Service - Assignment outside of section. Ignoring.

### ISSUE THREAD

**Issue by dexter74** [christgau/wsdd#180]
OS: Debian 12
Release:  Bookworm
Application: Proxmox PVE

![image](https://github.com/christgau/wsdd/assets/35907/62c47bd3-8ccc-4e93-8593-c23312c302de)

![image](https://github.com/christgau/wsdd/assets/35907/b7198044-18af-4cff-ab77-8488c8617878)

**Comment by christgau** [comment]
Do you use the wsdd package from the official Debian repo or did you installed wsdd and its service file on your own?

**Comment by JedMeister** [comment]
If you installed from default Debian, then you have a (buggy/incomplete) drop in service file (in `/etc`) that is overriding the default.

I say that because the Debian [wsdd package](https://packages.debian.org/bookworm/wsdd) doesn't have `/etc/systemd/system/wsdd.service` (where the errors are, according to your log output) - instead it provides [ `/lib/systemd/system/wsdd.service`](https://packages.debian.org/bookworm/all/wsdd/filelist). If a file exists at `/etc/systemd/system/wsdd.service`, that will override the default provided by the package.

I'd recommend just trying to disable it and see if that solves your issues?:
```
sudo mv /etc/systemd/system/wsdd.service /etc/systemd/system/wsdd.service.disabled
sudo systemctl daemon-reload
sudo sysmtemctl restart wsdd
```
(Or something like that ... - that's OTTOMH and untested)

**Comment by JedMeister** [comment]
I suggest that you remove the third party repo and package, then just install the version from the official Debian repositories.

I.e. something like this (as root):
```
apt purge wsdd
mv /etc/apt/sources.list.d/wsdd.list /etc/apt/sources.list.d/wsdd.list.disabled
apt update
apt install -y wsdd
```

**Comment by christgau** [comment]
> If you installed from default Debian, then you have a (buggy/incomplete) drop in service file (in /etc) that is overriding the default.

Given that and since I don't see any issue the unit file in this repo, I'm closing this issue.

**Comment by christgau** [comment]
@dexter74, your [original post](https://github.com/christgau/wsdd/issues/180#issue-1804024902)  was on Bookworm. For older distros, please follow the guide in the Readme
