### ISSUE TITLE
Contribute Debian package

### ISSUE THREAD

**Issue by fxrb** [christgau/wsdd#19]
Hello,
Not an issue but I just couldn't find an mail address for my request.

I have created files to generate a wsdd Debian package. The package installs wsdd as service unit. wsdd's command line parameters are configurable by the file /etc/wsdd.conf.
It would be my pleasure to contribute this to wsdd.

regards Felix

**Comment by christgau** [comment]
Thanks for your work, Felix. Is your package available anywhere? 

There has been a discussion on the [Ubuntu Bugtracker](https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1831441) to include wsdd in that distro. In the third comment it is argued that a Debian package may would make more sense. So it might be a good opportunity for you to jump in and fill that gap. 

From my side, I would prefer to not include any distro-specific package in this repo in order to have a clean separation for what is the pure software source code and what are packages for specific distros. Correct me if I'm wrong, but I think that this is the usual way to go.

In that sense, I'd like to notice that I already maintain an unofficial [Gentoo package](https://github.com/christgau/wsdd-gentoo) which I try to push into the distro. For Arch there is also a [user-contributed package](https://aur.archlinux.org/packages/wsdd/). So, the Debian (und Ubuntu) community may welcome your contribution...

**Comment by fxrb** [comment]
Hello christgau,

> Is your package available anywhere?

Yes, the package is currently available in this repository https://pkg.ltec.ch/public.

> There has been a discussion on the [Ubuntu Bugtracker](https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1831441) to include wsdd in that distro. In the third comment it is argued that a Debian package may would make more sense. So it might be a good opportunity for you to jump in and fill that gap.

Thanks for this link. Probably that's in fact the way to go ahead for a wsdd Debian package.

> From my side, I would prefer to not include any distro-specific package in this repo in order to have a clean separation for what is the pure software source code and what are packages for specific distros. Correct me if I'm wrong, but I think that this is the usual way to go.

Agreed. It makes sense to keep the source code for package creation away from the wsdd source code. Especially since there are quiet a few different packaging systems around.

regards, Felix

**Comment by christgau** [comment]
> > Is your package available anywhere?
>
> Yes, the package is currently available in this repository https://pkg.ltec.ch/public.

Thanks for providing the link. 

> > There has been a discussion on the [Ubuntu Bugtracker](https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1831441) to include wsdd in that distro. In the third comment it is argued that a Debian package may would make more sense. So it might be a good opportunity for you to jump in and fill that gap.
> 
> Thanks for this link. Probably that's in fact the way to go ahead for a wsdd Debian package.

That really sounds good 😉

I'll keep that ticket open and assign it to you. It might be a good place to keep everyone informed of your progress in pushing a package for wsdd to Debian (or Ubuntu).

**Comment by jkroepke** [comment]
What about a ppa on launchpad?

**Comment by fxrb** [comment]
> What about a ppa on launchpad?

From what I know launchpad PPAs are more or less directly related to Ubuntu. I would prefer to see wsdd in the official Debian repository.

**Comment by iandonnelly** [comment]
Funny I was thinking about the same kind of thing. Do you have the source code for the package itself available?

**Comment by fxrb** [comment]
> Funny I was thinking about the same kind of thing. Do you have the source code for the package itself available?

What do you mean by "source code for the package itself"?
You can look at the source code I wrote to create the deb package by downloading the *.deb file from the link above and inspecting it with an archive manager. Please note: my code does **not at all** comply with the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/).

**Comment by fxrb** [comment]
Sorry, I accidently close the issue.

**Comment by christgau** [comment]
@fxrb FYI: I've added a note to the readme in the feat/discovery that is very like to be merged into master at some point in the future. The readme now references your packages for Ubuntu/Debian. Do feel fine with that?

**Comment by fxrb** [comment]
Yes, I'm perfectly fine that.

**Comment by christgau** [comment]
Great & Thanks.

**Comment by mjsir911** [comment]
Hi. I'm trying to use the linked debian repo on my raspberry pi but it is not working because the `armhf` architecture is not supported.

Seeing as how it's just python code and the architecture doesn't actually matter, could you add an `armhf` supported architecture there?

The code runs fine on my raspberry pi, would just like to have a packaged up version.

**Comment by fxrb** [comment]
I have added the `armhf` architecture to the repository and made the `wsdd` package available for all architectures supported by the repository.
Note that this might activate updates for already installed `wsdd` packages for all **other** architectures.

**Comment by cswboys** [comment]
Hey there! Thank you @christgau for this awesome creation, I am new to the linux world and was able to get his working on my new Ubuntu server install.

I was curious @fxrb, could I use the Ubuntu repo you setup for Ubuntu "Bionic" with the current version of Ubuntu server I'm using: "Focal" (20.04). I hope this question makes sense and i posted it in the right place. Thank you both again for making this possible!

**Comment by fxrb** [comment]
No worries your question makes sense and is posted at the right place.

An update from Ubuntu 18.04 to 20.04 of my development machine (and others in the company) will happen according to [Focal Fossa Release Notes](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes/Kubuntu): 

> From 18.04, upgrades will not be enabled until approximately the date of the 1st 20.04 point release at the end of July. 

So this will be the earliest point in time our Debian/Ubuntu repository will be update by the new codename for Ubuntu 20.04 (Focal Fossa).

Meanwhile this workaround could help:

1. download the **wsdd_0.5.0_all.deb** file from https://pkg.ltec.ch/public/pool/main/w/wsdd
2. right click the downloaded file and see if there is an option to _install_ it (with QApt Package Installer, for instance)
3. if 2. does not work, use _dpkg_ to install the downloaded file

Good luck, Felix

**Comment by cswboys** [comment]
Thank you so much for the quick reply!

I will wait for the new repo (i think im saying that right) to come online,
and thank you for the knowlege on why there is a wait time ( Focal Fossa
Release Notes <https://wiki.ubuntu.com/FocalFossa/ReleaseNotes/Kubuntu>).
In the meantime i have installed it manually and it is working perfectly!

Thank you again for your help and expertise!

Joel

**Comment by fxrb** [comment]
The repository  has been updated to make wsdd v0.6.1 available for Ubuntu 20.04 (Focal Fossa).

**Comment by cswboys** [comment]
Thank you so much for the update! I appreciate the follow up!

**Comment by RottenRonnie** [comment]
Would you be able to add support for the arm64 architecture? 

https://www.raspberrypi.org/blog/latest-raspberry-pi-os-update-may-2020/

> I have added the `armhf` architecture to the repository and made the `wsdd` package available for all architectures supported by the repository.
> Note that this might activate updates for already installed `wsdd` packages for all **other** architectures.

_Error Message on pi4 running 64bit beta raspbian OS Buster:_
`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://pkg.ltec.ch/public buster InRelease' doesn't support architecture 'arm64'`

I'd also like to suggest that the Read.Me contain instructions for the debian package on how to add the repository key:

You may also add the public key to the trusted ones on your system.
`# curl -L https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key | sudo apt-key add -`


Cheers!

**Comment by fxrb** [comment]
I have extended the the architecture list by **arm64** for the **buster** distribution.

**Comment by RottenRonnie** [comment]
> I have extended the architecture list by **arm64** for the **buster** distribution.

Thank you so much! Works like a charm! Installed on Raspbian OS 64bit beta, and when run in a terminal, the pi4 showed up in the the network of my Windows 10 Home client. 

Cheers! 



```
pi@pi4:~ $ wsdd
2020-10-31 20:52:05,976:wsdd WARNING(pid 942): no interface given, using all interfaces
```
![2020-10-31 20_58_39-Window](https://user-images.githubusercontent.com/10812745/97792385-37dd8c80-1bbc-11eb-801c-63ff2cc73b9c.png)

**Comment by fxrb** [comment]
Ubuntu on Raspberry Pi 4?
Okay, I have extended the architecture list by **arm64** for the **focal** distribution.

**Comment by christgau** [comment]
> Ubuntu on Raspberry Pi 4?

Seems to be possible https://ubuntu.com/download/raspberry-pi

**Comment by GoldenHashtag** [comment]
Can't proceed to update
![image](https://user-images.githubusercontent.com/40300931/102708420-fe80ed80-42dd-11eb-9cc3-abe4a243a252.png)
I've added public key
![image](https://user-images.githubusercontent.com/40300931/102708464-44d64c80-42de-11eb-9e2e-b1ff48b1a5c6.png)
 I'm running Ubuntu 20.04
![image](https://user-images.githubusercontent.com/40300931/102708486-88c95180-42de-11eb-92d1-1ba94fb8cc74.png)

**Comment by JedMeister** [comment]
Quoting https://github.com/christgau/wsdd/issues/19#issuecomment-544123776:
>> Funny I was thinking about the same kind of thing. Do you have the source code for the package itself available?
>
> What do you mean by "source code for the package itself"?
> You can look at the source code I wrote to create the deb package by downloading the *.deb file from the link above and inspecting it with an archive manager. Please note: my code does not at all comply with the Debian Policy Manual.

@fxrb - I assume that @iandonnelly was referring to the source `debian` directory that contains the Debian packaging config and files.

You suggest that unpacking the deb file will reveal the "source code [you] wrote", but unless you are using some particularly arcane method to produce your packages, then I doubt that's actually the case.

Obviously unpacking the deb file will show the files used to install the software (some which may have even been explicitly created by you), but not all. You do note that your package isn't compatible with Debian policy, so perhaps your packaging files are simple (and your method of building packages dramatically different to what I've experienced) and that's exactly what is included in your deb? Although, I note that the systemd service file from your package does not match the one here in the repo. So you must at least have a separate copy of that somewhere?!

Regardless, I agree with @iandonnelly. Even if what is in the deb file is exactly what is in your packaging source code (which I'd be surprised by), in the spirit of open source and collaboration, the packaging should be publicly available. Ideally IMO it should be via a repo here on GH, so that others can see it at a glance and potentially even improve it (perhaps to the point where it is compliant with Debian policy and can be included in Debian default repos, and by extension will land in Ubuntu's too?!).

I note too that [OpenMediaVault](https://www.openmediavault.org/) have a [fork of the code](https://github.com/openmediavault/wsdd), in which they include a [`debian` directory](https://github.com/openmediavault/wsdd/tree/master/debian). They build a [Debian package (`wsdd_0.6.2-1_all.deb`)](https://github.com/openmediavault/packages/raw/master/pool/main/w/wsdd/wsdd_0.6.2-1_all.deb) from it. So it's not as new as your package, but they have published their source.

**Comment by christgau** [comment]
> Ideally IMO it should be via a repo here on GH, so that others can see it at a glance and potentially even improve it (perhaps to the point where it is compliant with Debian policy and can be included in Debian default repos, and by extension will land in Ubuntu's too?!).

I would highly appreciate and support such an initiative and joint efforts.

**Comment by fxrb** [comment]
> Quoting [#19 (comment)](https://github.com/christgau/wsdd/issues/19#issuecomment-544123776):
> 
> > > Funny I was thinking about the same kind of thing. Do you have the source code for the package itself available?
> > 
> > 
> > What do you mean by "source code for the package itself"?
> > You can look at the source code I wrote to create the deb package by downloading the *.deb file from the link above and inspecting it with an archive manager. Please note: my code does not at all comply with the Debian Policy Manual.
> 
> @fxrb - I assume that @iandonnelly was referring to the source `debian` directory that contains the Debian packaging config and files.
> 
Unfortunately @iandonnelly never answered my question so we don't know. If so it would be 'DEBAIN' and not 'debian' as the package is a binary package using [Binary package control files](https://www.debian.org/doc/debian-policy/ch-controlfields.html#binary-package-control-files-debian-control). Source packages share another purpose but I'm not going into further details here.

> You suggest that unpacking the deb file will reveal the "source code [you] wrote", but unless you are using some particularly arcane method to produce your packages, then I doubt that's actually the case.
> 
Your doubts are unfounded. Unpacking the deb file will also reveal an archive named `control.tar.xz` which contains all control files from the 'DEBIAN' directory used for packaging.
We use a handcrafted bash script to generate deb packages (not only for wsdd). This script does compressing, stripping, etc. and finally also uses `dpkg-deb` to build the package. If you call this arcane, well, okay.

> Obviously unpacking the deb file will show the files used to install the software (some which may have even been explicitly created by you), but not all.
>
Actually unpacking the deb file will show **all** files.

> You do note that your package isn't compatible with Debian policy, so perhaps your packaging files are simple (and your method of building packages dramatically different to what I've experienced) and that's exactly what is included in your deb?
>
Yes.

>Although, I note that the systemd service file from your package does not match the one here in the repo. So you must at least have a separate copy of that somewhere?!
> 
There is no such thing as a "separate copy somewhere", why should that be the case? The file you found in the package, that differs from the one you find in the wsdd repository here, _is_ a file I added or modified. So you got the source in your hands! QED.

> Regardless, I agree with @iandonnelly. Even if what is in the deb file is exactly what is in your packaging source code (which I'd be surprised by), in the spirit of open source and collaboration, the packaging should be publicly available. Ideally IMO it should be via a repo here on GH, so that others can see it at a glance and potentially even improve it (perhaps to the point where it is compliant with Debian policy and can be included in Debian default repos, and by extension will land in Ubuntu's too?!).
> 
Agreed. As I'm also contributing to the LINUX and the U-Boot project I'm quite familiar with the "spirit of open source and collaboration". Getting a package compliant with the Debian policy however is not a snap. And yes, for a package _conforming_ with the Debian policy there will be a bunch of "other" files not included in the deb file. But as already stated: my actual wsdd package is **not** compliant with the Debian policy.

> I note too that [OpenMediaVault](https://www.openmediavault.org/) have a [fork of the code](https://github.com/openmediavault/wsdd), in which they include a [`debian` directory](https://github.com/openmediavault/wsdd/tree/master/debian). They build a [Debian package (`wsdd_0.6.2-1_all.deb`)](https://github.com/openmediavault/packages/raw/master/pool/main/w/wsdd/wsdd_0.6.2-1_all.deb) from it. So it's not as new as your package, but they have published their source.
>
Why not clone that repository then and just replace the `wsdd.py` script? I personally doubt it will be that simple but it could be worth a try :wink: .

**Comment by JedMeister** [comment]
FWIW whilst I'm far from an expert, I'm fairly familiar with Debian packaging. I maintain a repo myself. Many of our packages should be Debian compliant, but some certainly aren't (we we tweak the source code in non-standard ways).

I have always intended to get more involved with official Debian packaging, but I never seem to have the spare cycles to fill in the knowledge gaps I have.

> [...] it would be 'DEBAIN' and not 'debian' as the package is a binary package using Binary package control files.

AFAIK, it should be `debian` (i.e. lower case) in the package source. I'm talking about the source code that is used to generate the Debian binary &/or source packages (as you rightly point out, the source package will include the `debian` directory from the package build source code). By convention, the `DEBIAN` directory in the binary package is generated (from the `debian` directory) by the package building process.

>Unpacking the deb file will also reveal an archive named control.tar.xz which contains all control files from the 'DEBIAN' directory used for packaging.

Yeah, while I was trying to work out what you'd done, I [compared the contents](https://github.com/JedMeister/wsdd/tree/deb_pkg_contents) of your package against the contents of the OpenMediaVault one.

FWIW, you may already be aware, but IMO a quicker/easier way to unpack deb packages (rather than using `ar` and `tar`) is:
```
dpkg-deb -R <pkg>.deb <tmp_dir>
```

Or if you just want the contents of `control.tar.xz` (or `control.tar.gz` as the case may be):
```
dpkg-deb -e <pkg>.deb <tmp_dir>
```

>We use a handcrafted bash script to generate deb packages (not only for wsdd). This script does compressing, stripping, etc. and finally also uses dpkg-deb to build the package. If you call this arcane, well, okay.

Ah ok. This note that you've scripted a manual package construction process, certainly explains things. :smile:

Sorry I didn't mean to offend by my use of 'arcane', but I would argue that unless you are publishing the custom script(s) that you use to produce your packages (or at least explaining the process in detail) your custom build process _is_ arcane by definition: 

> arcane (ɑːˈkeɪn/)
>
>adjective:
>
> **understood by few; mysterious or secret.**

:wink:

With that knowledge, I totally get why your package isn't compliant with Debian policy!

I would urge you to look into the use of "proper" package building tools, such as [`sbuild`](https://packages.debian.org/buster/sbuild), [`pbuilder`](https://packages.debian.org/buster/pbuilder), [`git-buildpackage`](https://packages.debian.org/buster/git-buildpackage), or even `dpkg-buildpackage` (from [`dpkg`](https://packages.debian.org/buster/dpkg)) and `debuild` (from [`devscripts`](https://packages.debian.org/buster/devscripts)), etc (there's quite a few; AFAIK most are wrappers around `pbuilder` or `sbuild`). That way, so long as you set up your source directory correctly (particularly the `rules` & `*.install` files in the `debian` dir), most of the work is automagical.

FYI we use `pbuilder` for our package building, although we have a custom wrapper around it (called [deckdebuild](https://github.com/turnkeylinux/deckdebuild)) which leverages overlayfs to build the package within a copy-on-write chroot of a local pre-existing buildroot.

> Agreed. As I'm also contributing to the LINUX and the U-Boot project I'm quite familiar with the "spirit of open source and collaboration".

Ok cool. Again, apologies if my comment caused offence. It didn't occur to me that you were essentially building packages in a completely custom way.

> Getting a package compliant with the Debian policy however is not a snap. And yes, for a package conforming with the Debian policy there will be a bunch of "other" files not included in the deb file. But as already stated: my actual wsdd package is not compliant with the Debian policy.

Trying to build a package compliant with Debian policy using custom scripts would certainly be a nightmare! But if you instead use one of the many existing tools within Debian, then most of the hard work is done for you and it'll be a whole lot easier... :wink:

> Why not clone that repository then and just replace the wsdd.py script? I personally doubt it will be that simple but it could be worth a try :wink: .

Funny you suggest that... :smile: And yeah, it is that simple! :smile: 

After I posted here the other day, I more-or-less did that. FYI I created a [new repo](https://github.com/JedMeister/wsdd) with `master` branch tracking `master` of this repo, and a [`openmediavault-master` branch](https://github.com/JedMeister/wsdd/tree/openmediavault-master) tracking `master` of the OpenMediaVault repo (which includes teh `debian` dir). I then created a new [`turnkey-packaging` branch](https://github.com/JedMeister/wsdd/tree/turnkey-packaging) (forked from `openmediavault-master`). In that branch, I rebased on the most recent release of wsdd (i.e. I rebased on the `v0.6.4` tag in `master`) and made a [few packaging tweaks](https://github.com/JedMeister/wsdd/compare/437236b...e12d5cd).

As I've mentioned, I'm certainly no packaging expert, so I'm sure that there are plenty more improvements to be made... (E.g. I don't actually think that I need to explicitly be installing `dh-exec` when using debhelper >= 12; most of my experience is with debhelper <= 10). There are also more opinionated changes (to the packaging code provided by OpenMediaVault) that I'd like to make, such as either moving/renaming `/usr/sbin/wsdd.py` to `/usr/sbin/wsdd`, or perhaps putting `wsdd.py` in `/usr/lib` and symlinking `/usr/sbin/wsdd` but it's not too bad as is IMO.

Because of the way that the source dir is constructed (i.e. `debian` dir added to upstream source in a third party fork), this is still not really acceptable into Debian. (Although FWIW if @christgau included the `debian` directory, then it'd probably be reasonable to consider it a "native" Debian package source and it'd be good to go as is I reckon, not withstanding perhaps a few `debian` tweaks...).

If you are at all interested in the package that I built (from [my fork - with the tweaked `debian` dir](https://github.com/JedMeister/wsdd/tree/turnkey-packaging) - using the `pbuild` wrapper I mentioned earlier - you can find it [here](http://archive.turnkeylinux.org/debian/pool/buster/main/w/wsdd/wsdd_0.6.4%2bturnkey0_all.deb).

**Comment by STrRedWolf** [comment]
Can we get updates for Ubuntu on "groovy" and "hirsute" (20.10 and 21.04)?  I got a Pi 4 and a few x86-64 VMs with 20.10 and I'll be going to 21.04 as soon as they fix the EFI issues.

**Comment by fxrb** [comment]
The repository will support LTS versions only, so no.

**Comment by christgau** [comment]
Thanks @JedMeister for your efforts and explanations. 

> Because of the way that the source dir is constructed (i.e. `debian` dir added to upstream source in a third party fork), this is still not really acceptable into Debian. (Although FWIW if @christgau included the `debian` directory, then it'd probably be reasonable to consider it a "native" Debian package source and it'd be good to go as is I reckon, not withstanding perhaps a few `debian` tweaks...).

Does that mean that every open source project that wants to get into Debian is required to have a `debian` directory in the root of its source tree? That sounds a little strange to me.... or - more frankly speaking - is an egocentric perspective from Debian. Why isn't it acceptable to have a repository like yours which is based on the original source tree and then have the required files for the package build added to that. Having no idea of what the structure has to look like, wouldn't it be an alternative to have, e.g., a git-based repo with the package build files and a git submodule for the actual source code (or use some kind of download to fetch the source code),

I ask this because I want to avoid having build code for all those different OS/distributions out there in this repository. Such a "build-bloat repo" might also imply having code or directory tree adjustments for the different target distros which potentially collide with each other. 

Coming from the Gentoo world, where packages for a particular software basically fetch the vanilla source code from the software's origin (e.g. this github repo), possibly patch it, and finally compile it, it looks kind of awkward to "force" upstream to follow distro-specific guidelines.

I'd like to iterate on this a little more in order to get a proper solution... and finally an acceptable Debian/Ubuntu package. Can you provide some resources on the requirements for acceptable Debian packages?

**Comment by JedMeister** [comment]
Hey @christgau, no problem at all.

I'll answer some of your questions to the best of my ability below. But please keep in mind, whilst I do have a fair bit of experience with Debian and packaging, I'm not a Debian Developer/Maintainer. Whilst I do have some internal Debian contacts, and some insight, I've never actually been involved in any official Debian package.

> Does that mean that every open source project that wants to get into Debian is required to have a debian directory in the root of its source tree?

No, not at all. And that's certainly not the common way of doing it. AFAIK historically the most common way of doing it was a source tarball, with a `.dsc` (debian source changes IIRC?!) file. But if a source does have a `debian` directory, then it can be considered a "native" package". So can exist in a single repo, instead of the `debian` directory being in a separate branch.

>Why isn't it acceptable to have a repository like yours which is based on the original source tree and then have the required files for the package build added to that.

Well, it does appear to be acceptable these days, but I'm not clear on when that changed, nor what the specific requirements are for that to be acceptable. Even then though, there still needs to be a "pristine" branch that directly follows upstream. That way any changes to the source can be explicit. The idea is that there should be maximum transparency and a clear separation between what the upstream developer (you in this case) is doing and what others (such as me) are doing. Unless of course, if upstream and the packager are the same (then a "native" package is acceptable).

>Having no idea of what the structure has to look like, wouldn't it be an alternative to have, e.g., a git-based repo with the package build files and a git submodule for the actual source code (or use some kind of download to fetch the source code),

You could, but usually, as I hinted/noted above, it's done in a separate branch rather than as a submodule.

>I ask this because I want to avoid having build code for all those different OS/distributions out there in this repository. Such a "build-bloat repo" might also imply having code or directory tree adjustments for the different target distros which potentially collide with each other.

Yeah for sure, if you're not a Debian user and/or you plan to have it packaged for everything, I think that totally make sense!

>I'd like to iterate on this a little more in order to get a proper solution... and finally an acceptable Debian/Ubuntu package. Can you provide some resources on the requirements for acceptable Debian packages?

No worries. TBH, I'm hoping to finally get my act together and actually get more involved with Debian packaging. With the hard freeze well and truly in place and the RC bugs getting lower by the day, I imagine that now is probably not a great time to try to get a new package into Debian (although perhaps I'm wrong?!). Re getting it into Ubuntu, I'm not 100% clear how that works. I was originally under the impression that if it's in Debian, it'll end up in Ubuntu, but Debian has significantly more packages, so I don't think that is the case.

Re packaging, I think that this [wiki page](https://wiki.debian.org/Packaging) is probably the best place to start. But if you want to have a go at it yourself, then I suggest reading first, then do some playing around and get it all working as you want. Once you have a bit of a feel for it and your package is pretty much ready to go (in your opinion), then ask for a review of what you've done and a sponsor (who can help you get the actual package into the repos) on the [Debian mentors mail list](https://lists.debian.org/debian-mentors/).

Good luck and I look forward to hearing how things go. Also FWIW, I think that there are a few improvements that could be made to the current package that I have.

**Comment by fxrb** [comment]
The repository has been updated to make wsdd v0.6.4 available for Debian 11.0 (bullseye).

**Comment by fxrb** [comment]
The repository has been updated to wsdd v0.7.0.

**Comment by grantma** [comment]
Hi!  I am a full DD just packaging wsdd for Debian.  In the process of putting the latest tarball for 0.7.0 into the salsa git package I am building.

@fxrb, @JedMeister: why the python 3.9+ source typing and changes you made on top of 0.7.0 please, touches whats in github repo allover the place.  Does what you do handle interface going up and down without having to restart daemon etc?  Your reasons please, and Christian, are you going to upstream these changes into 0.7.1 at all?

**Comment by JedMeister** [comment]
@grantma 

> Hi! I am a full DD just packaging wsdd for Debian. In the process of putting the latest tarball for 0.7.0 into the salsa git package I am building.

Awesome!

> why the python 3.9+ source typing and changes you made on top of 0.7.0 please, touches whats in github repo allover the place.

Not sure what you are referring to? BTW, I haven't made any updates to the [repo](https://github.com/JedMeister/wsdd) I threw together (forked this code and added debian dir) since 0.6.4.

> Does what you do handle interface going up and down without having to restart daemon etc?

I haven't made any modifications to support that explicitly. I haven't tested that, so I have no idea.

> Your reasons please

Again, I need some clarification on what you are asking.

**Comment by grantma** [comment]
Debian package of wsdd 0.7.0 now in Debian unstable, packaged correctly.  Also uploaded to backports for bullseye.  Package repository is up at https://salsa.debian.org/debian/wsdd if you want to package for older Ubuntu etc.

Please, this is the OFFICIAL package.  Christian please have a look and I will fix things up.

**Comment by JedMeister** [comment]
> Debian package of wsdd 0.7.0 now in Debian unstable, packaged correctly. Also uploaded to backports for bullseye. Package repository is up at https://salsa.debian.org/debian/wsdd if you want to package for older Ubuntu etc.

Nice work. Although it looks like the repo isn't public? (I get redirected to a login screen).

**Comment by grantma** [comment]
Repo is actually at:

https://salsa.debian.org/grantma/wsdd

Searching for it would have found it as well.

**Comment by grantma** [comment]
It's a bit rough, (eg debian/rules not swish), but its a starting point :-)

**Comment by grantma** [comment]
Got it in unstable uploads queue a week ago, now it been accepted into Debian Unstable Sid.  Will hopefully go into testing shortly. Won't be in Ubuntu 22.04 LTS unfortunately though unless someone makes a stink about it to Ubuntu....

**Comment by panlinux** [comment]
It got pulled in and is in 22.04 LTS universe \o/
https://launchpad.net/ubuntu/+source/wsdd

**Comment by christgau** [comment]
Thanks a lot for the packaging work on wsdd, @grantma. Since packages are underway for Debian (and maybe [?] Ubuntu) I finally close this issue. 

And also thanks to @fxrb for providing his packages since the early days of this issue. Do you intent to keep wsdd in your repo (for the older distros)?

**Comment by grantma** [comment]
I should be able to get in backports for Debian Bullseye and LTS if python3
there is up to it :-)  Lets let it get to Debian testing first for wee
while though.

**Comment by fxrb** [comment]
@christgau thanks to you for providing wsdd!
I plan to keep wsdd in the the package repository at least until it it is available in **Debian stable** and **Ubunutu LTS**. 
For now I will try to keep updating the repository and use this thread to notify about those updates, if you don't mind.

**Comment by mundodisco8** [comment]
Hi! Thanks for your work packing the app. I tried to install it on a Raspberry Pi 4 running the latest Raspbian (Bullseye) and apt seems unable to find the package. I opened an issue (#132) and @christgau's response lead me to this issue.

**Comment by JedMeister** [comment]
@grantma

You're probably already aware, but in case you missed it, I just noticed that `wsdd` hasn't made it into 'bookworm' yet (https://tracker.debian.org/pkg/wsdd). It appears that it's stuck in 'sid' with some packaging issue, [namely](https://qa.debian.org/excuses.php?package=wsdd):

>Issues preventing migration:
>    - Not built on buildd: arch all binaries uploaded by grantma, a new source-only upload is needed to allow migration

It'd be great if you could get it into `bullseye-backports`.

**Comment by christgau** [comment]
@fxrb, @grantma Since official packages for Debian and Ubuntu LTS are available, would you agree to close that issue?

**Comment by fxrb** [comment]
Yes, for me that's fine, feel free to close this issue.
If I find some time in future I will remove the relevant parts from the repository. Hence you should probably remove the section _others_ from the installation instructions.
