### ISSUE TITLE
Systemctl service failed to start

### ISSUE THREAD

**Issue by GabiGunner** [christgau/wsdd#193]
I have a fedora 39 server set up, hooked up to the internet only by ethernet.
output of `sudo systemctl status wsdd`:

```
× wsdd.service - Web Services Dynamic Discovery host daemon
     Loaded: loaded (/usr/lib/systemd/system/wsdd.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: resources)
       Docs: man:wsdd(8)
        CPU: 0

Jan 13 19:51:49 localhost.localdomain systemd[1]: wsdd.service: Failed to load environment files: No such file or directory
Jan 13 19:51:49 localhost.localdomain systemd[1]: wsdd.service: Failed to run 'start' task: No such file or directory
Jan 13 19:51:49 localhost.localdomain systemd[1]: wsdd.service: Failed with result 'resources'.
Jan 13 19:51:49 localhost.localdomain systemd[1]: Failed to start wsdd.service - Web Services Dynamic Discovery host daemon.

```

output of `sudo journalctl -xeu wsdd.service`:

```
Jan 13 19:51:49 localhost.localdomain systemd[1]: wsdd.service: Failed to load environment files: No such file or directory
Jan 13 19:51:49 localhost.localdomain systemd[1]: wsdd.service: Failed to run 'start' task: No such file or directory
Jan 13 19:51:49 localhost.localdomain systemd[1]: wsdd.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit wsdd.service has entered the 'failed' state with result 'resources'.
Jan 13 19:51:49 localhost.localdomain systemd[1]: Failed to start wsdd.service - Web Services Dynamic Discovery host daemon.
░░ Subject: A start job for unit wsdd.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit wsdd.service has finished with a failure.
░░ 
░░ The job identifier is 1907 and the job result is failed.

```

![Screenshot from 2024-01-13 23-34-55](https://github.com/christgau/wsdd/assets/101864779/e5a84cbd-42ed-491e-a3e2-1300869f1958)

![Screenshot from 2024-01-14 10-24-19](https://github.com/christgau/wsdd/assets/101864779/6d33f522-feaf-425f-9bda-8740290526e7)

**Comment by christgau** [comment]
I'd like you to consider checking the error messages carefully and act accordingly. It states:

> Failed to load environment files: No such file or directory

If you take a look into the unit file, there is probably a line referencing an environment file, just like here: https://github.com/christgau/wsdd/blob/563d7933f9e81385eba14c3108474aab6f324410/etc/systemd/wsdd.service#L15

Note that the actual path in your installation may differ. Then check if the file referenced in your unit file exists, otherwise create it (can be empty). If it is really missing, you should create a bug at Fedora as this may either a bug in the Fedora packaging or in your installation.

That being said it is not an issue of wsdd per se. Thus, I close this issue:

PS: Please try searching the web for the error messages before creating an issue for such an apparent and non-unique or wsdd-specific problem.
