### ISSUE TITLE
Move manpage back to section 1

### ISSUE THREAD

**Issue by jbicha** [christgau/wsdd#198]
The manpage was moved to section 8 without explanation in https://github.com/christgau/wsdd/commit/bfc2b4218fadfb02f9dc8cd539f12276d9fbe61b and https://github.com/christgau/wsdd/commit/c87819bda08acbe5913057770cc393c788577fb7

Please move it back. According to the [man-pages documentation](https://man7.org/linux/man-pages/man7/man-pages.7.html), section 8 is for system management commands, many of which require root to execute.

wsdd can be used in listen mode and this does not require root. Nor is this a system management command but a regular user command.

**Comment by christgau** [comment]
> According to the [man-pages documentation](https://man7.org/linux/man-pages/man7/man-pages.7.html), section 8 is for system management commands, many of which require root to execute.

True, but `intro(8)` also states:

> Section 8 of the manual describes commands which either can be or are used only by the superuser, like system-administration commands, **daemons**, and hardware-related commands.

The default use case for wsdd is to be run as a daemon, thus it was moved into this section. Therein you also find the man pages of other daemons (if installed), like nginx, mysql, or smbd.

In addition, the question of whether a system is discoverable via WSD is a system wide decision. Technically, it cannot be a user's decision on a multi-user system. Thus, the system administrator (someone with root privileges) is the one that in most cases will deal with wsdd.

> wsdd can be used in listen mode and this does not require root. 

I assume you are referring to the discovery mode where one can look for other WSD hosts in the network. In that sense your statement is true and wsdd may be considered as a hybrid because it combines both host and client roles of the protocol. In the end, I see the primary and default use case in the host role/daemon (see above). 

PS: I don't recall exactly, but I think the move was also motivated by what the Debian package for Bookworm does for [v0.7.0](https://github.com/christgau/wsdd/tree/v0.7.0): https://packages.debian.org/source/bookworm/wsdd. It patches the man page and moves it to section 8 which I find reasonable, apparently.

> Nor is this a system management command but a regular user command.

See above, in first place wsdd, as its name suggest, is a daemon. As such, I find section 8 the better place.
