### ISSUE TITLE
Question about `is_multicastable`

### ISSUE THREAD

**Issue by kristof-mattei** [christgau/wsdd#217]
As I was studying the code (as one does on a Saturday morning) I'm not sure I understand the `is_multicastable` function:

https://github.com/christgau/wsdd/blob/486e054ec73bc12a79d465d1fbd0c11c12b0f014/src/wsdd.py#L113-L119

To my understanding the code marks IPv4 addresses starting with `127` as multicastable, which contradicts the ranges specified in https://datatracker.ietf.org/doc/html/rfc3171#section-2

```python
>>> raw = socket.inet_pton(2, "127.0.0.0")
>>> raw[0] == 127
True
```

And I'm not sure it actually matches the older code found here:

https://github.com/christgau/wsdd/blob/5c184f3149804579932c0ce860e0ed35c724d121/src/wsdd.py#L939-L952

Where there is an explicit ignore of the loopback address.

**Comment by christgau** [comment]
> And I'm not sure it actually matches the older code found here:

Semantically the original code from back in the days is/was identical to the member function of `NetworkAddress`, as the checks were simply moved. However, the naming was bad. Now, the naming is still the same, but semantics have been fixed in [7398726](https://github.com/christgau/wsdd/commit/73987267940f2cfb45e1a74f89c95806f8d6df0b). 

> To my understanding the code marks IPv4 addresses starting with 127 as multicastable, which contradicts the ranges specified in https://datatracker.ietf.org/doc/html/rfc3171#section-2

Yes and no (see above). The purpose of the function is to check if one can create a multicast socket for the given address. It does not make sense to send multicast messages or create according sockets on a (legacy IP) loopback interface (check for 127/8). In addition, the service is intended to be used on local networks only. That's why there's a check for IPv6 link local addresses. 

Note that the function is not intended to match the IANA assignments, but the applications purposes.
