### ISSUE TITLE
Push ebuilds upstream

### ISSUE THREAD

**Issue by ismell** [christgau/wsdd#61]
I would like to get this included in the official portage repo. Has this been attempted? Would you be opposed? I can send a PR to official gentoo if you want with the ebuilds.

Thanks!

**Comment by christgau** [comment]
This issue might be better placed in christgau/wsdd-gentoo and, in fact, there is already an issue related to this one: https://github.com/christgau/wsdd-gentoo/issues/2... As a result of that request over there, there is an PR to get into the Gentoo repo: https://github.com/gentoo/gentoo/pull/12393. It lingered around for a while and I was asked to push the ebuilds in the Guru tree. That's their home right now. 

Please continue the discussion in https://github.com/christgau/wsdd-gentoo/issues/2 or in the ProxyMaintainer PR, I'm closing that one as invalid, because it is distro-specific and more related to project mentioned above.
