### ISSUE TITLE
unbound prefix error

### ISSUE THREAD

**Issue by sekyHC** [christgau/wsdd#71]
Hi. I am getting some strange errors on my open media vault server. If you tell me how to get better logs or what to do to debug it I will do it.

What I have so far:
```
seky@omv:/etc$ python3 /usr/sbin/wsdd.py --shortlog --workgroup=WORKGROUP -v -i enp1s0f0
INFO: using pre-defined UUID ...
INFO: joined multicast group ('239.255.255.250', 3702) on 192.168.8.2%enp1s0f0
ERROR: error in main loop
Traceback (most recent call last):
  File "/usr/sbin/wsdd.py", line 812, in serve_wsd_requests
    key.data.handle_request()
  File "/usr/sbin/wsdd.py", line 447, in handle_request
    msg = wsd_handle_message(msg, self.interface, address)
  File "/usr/sbin/wsdd.py", line 394, in wsd_handle_message
    tree = ElementTree.fromstring(data)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: unbound prefix: line 2, column 389
ERROR: error in main loop
Traceback (most recent call last):
  File "/usr/sbin/wsdd.py", line 812, in serve_wsd_requests
    key.data.handle_request()
  File "/usr/sbin/wsdd.py", line 447, in handle_request
    msg = wsd_handle_message(msg, self.interface, address)
  File "/usr/sbin/wsdd.py", line 394, in wsd_handle_message
    tree = ElementTree.fromstring(data)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: unbound prefix: line 2, column 389

```

**Comment by christgau** [comment]
Looks like you are using an older version of wsdd. It appears the version you are using is 0.5. Could you (manually) update wsdd to the latest release or master (doesn't make a difference)? Just do a clone/download of the repo, stop the wsdd service of your OMV installation and then run wsdd manually from the command line. 

The problem may very likely still be present in that version. To dig deeper, a call to `print(msg)` is needed before that line here https://github.com/christgau/wsdd/blob/4755c23430ce9bb508a3ac0b81cb5b21ed2a07bc/src/wsdd.py#L335 

You can omit the `-v` option then but it won't hurt as well.

My assumption is that this might be a fundamental problem using Python's ElementTree... :-/

**Comment by christgau** [comment]
As the problem arose again in #124 by @spindles7 I assume the following is going on:

There might devices on the network which neither run Linux with wsdd nor Windows. They may emit messages with an XML payload that contains namespaces which Python's ElementTree refuses to handle since wsdd didn't tell it to handle them. These messages might be legitimate, i.e. valid WSD messages with additional/other namespaces (or URIs), but they may be invalid as well. 

In the latter case, the error could be just ignored (and logged). Then we could silence the error messages.

In the former case, we have to exclude Windows as a source of messages that wsdd currently does not understand. If required wsdd needs to be aware of additional namespaces to handle valid messages. To do dig deeper I need some more input, especially the content of the invalid message. With the current release (v0.7.0) a `print(msg)`  or `logger.error("invalid XML message: {}".format(msg))` before the return statement would dump the content of the message of interest.

https://github.com/christgau/wsdd/blob/c9cffc5ecadf991e111b7f2b4bb4b3151d3a5635/src/wsdd.py#L363-L364

**Comment by christgau** [comment]
Please also note that the error message should disappear with v0.7.0 released a week ago.

**Comment by christgau** [comment]
Closing this issue, since there hasn't been any update and silencing the error messages appears to be what the OP wanted. Without knowing which other namespaces could be registered, there is hardly a chance to solve the "unbound prefix" error message and successfully parse the XML. Windows does not appear to be the reason for that issue- At least there nor complaints/reported issues by other users. Thus, the primary functionality (announcing hosts to Windows) seems to be still provided by wsdd.
